### ISSUE TITLE
shop restriction

### ISSUE THREAD

**Issue by Ultrunz** [HumanTree92/esx_truckshop#1]
I dont know if its just specific to your script but im sure it doesnt work on the esx_vehicleshop too.

i have been trying to get this to actually work. im still able to exit the vehicle
```
function StartShopRestriction()

    Citizen.CreateThread(function()
        while IsInShopMenu do
            Citizen.Wait(1)
    
            DisableControlAction(0, 75,  true) -- Disable exit vehicle
            DisableControlAction(27, 75, true) -- Disable exit vehicle
        end
    end)

end
```

I have tried a few iterations of this trying to disable being able to exit the car and also backspace `177` but i can add that as soon as it works.

just curious if there is a fix or alternative to this

**Comment by HumanTree92** [comment]
None that i know of. The Disabling exit vehicle works for me just fine.
