### ISSUE TITLE
Spawn problem

### ISSUE THREAD

**Issue by Adycter** [HumanTree92/esx_truckshop#2]
Hello, I use this truckshop script. When I already buy it, then I storage it to garage( I use advancedgarage). If I want to spawn it, there's nothing at my garage.

##edit : Every vehicle that I bought from truckshop is saved at owned_vehicles. But I cant spawn it from my garage.

**Comment by HumanTree92** [comment]
Make sure your using the latest update. Please send a picture of the structure of your owned_vehicles

**Comment by Adycter** [comment]
Heee is my own owned_garage

**Comment by HumanTree92** [comment]
I don't see the image. So you can count me out for support until you upload a proper image.

**Comment by HumanTree92** [comment]
You can reopen once you send the proper image

**Comment by Adycter** [comment]
Hello sorry for late respond, how to screenshot properly? should I give my
owned_vehicle sql? or something else?

**Comment by Adycter** [comment]
[image: image.png]or like this?
