### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by kira80420** [HumanTree92/esx_truckshop#3]
hi i have a small problem with the key of the truck i buy but i do not get the keys sis you please could you help me?
![20190725111846_1](https://user-images.githubusercontent.com/52800766/61862367-0f051c80-aece-11e9-8ebe-e3ffc6ed7d53.jpg)

**Comment by HumanTree92** [comment]
Thats b/c if you where smart you would realize that those a Custom Trucks. I have fixed the sql to help you dumb fuckers.
